import React from 'react'

function TeenPattiC() {
  return (
    <div>
      

      <div className="center-main-container casino-page"><div className="center-container"><div className="casino-page-container teenpatti20"><div className="casino-header"><span className="casino-name">20-20 Teenpatti C<a className="ms-1"><small>Rules</small></a></span><span className="casino-rid d-none d-xl-inline-block"><small>Round ID: <span>164250107142841</span></small></span></div><div className="casino-title-header-mobile d-xl-none"><ul className="nav nav-tabs menu-tabs"><li className="nav-item"><div className="nav-link active">Game</div></li><li className="nav-item"><div className="nav-link">Placed Bet (0)</div></li></ul><div className="pe-2"><span className="casino-rid">Round ID: <span>164250107142841</span></span></div></div><div className=""><div className="casino-video"><div className="video-box-container"><div className="casino-video-box">
     
     </div></div><div className="casino-video-cards"><div className=""><h5 className="">Player A</h5><div className="flip-card-container"><div className="flip-card"><div className="flip-card-inner "><div className="flip-card-front">
 <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/cards/KDD.jpg" /></div><div className="flip-card-back">
   <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/cards/KDD.jpg" /></div></div></div><div className="flip-card"><div className="flip-card-inner "><div className="flip-card-front">
     <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/cards/1.jpg" /></div><div className="flip-card-back">
       <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/cards/1.jpg" /></div></div></div><div className="flip-card"><div className="flip-card-inner "><div className="flip-card-front">
         <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/cards/1.jpg" /></div><div className="flip-card-back">
           <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/cards/1.jpg" /></div></div></div></div></div><div className="mt-1"><h5 className="">Player B</h5><div className="flip-card-container"><div className="flip-card"><div className="flip-card-inner "><div className="flip-card-front">
             <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/cards/1.jpg" /></div><div className="flip-card-back">
               <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/cards/1.jpg" /></div></div></div><div className="flip-card"><div className="flip-card-inner "><div className="flip-card-front">
                 <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/cards/1.jpg" /></div><div className="flip-card-back">
                   <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/cards/1.jpg" /></div></div></div><div className="flip-card"><div className="flip-card-inner "><div className="flip-card-front">
                     <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/cards/1.jpg" /></div><div className="flip-card-back">
                       <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/cards/1.jpg" /></div></div></div></div></div></div><div className="clock flip-clock-wrapper"><ul className="flip play"><li className="flip-clock-before"><a href="#"><div className="up"><div className="shadow"></div><div className="inn">1</div></div><div className="down"><div className="shadow"></div><div className="inn">1</div></div></a></li><li className="flip-clock-active"><a href="#"><div className="up"><div className="shadow"></div><div className="inn">0</div></div><div className="down"><div className="shadow"></div><div className="inn">0</div></div></a></li></ul><ul className="flip play"><li className="flip-clock-before"><a href="#"><div className="up"><div className="shadow"></div><div className="inn">1</div></div><div className="down"><div className="shadow"></div><div className="inn">1</div></div></a></li><li className="flip-clock-active"><a href="#"><div className="up"><div className="shadow"></div><div className="inn">0</div></div><div className="down"><div className="shadow"></div><div className="inn">0</div></div></a></li></ul></div></div><div className="casino-detail"><div className="casino-table"><div className="casino-table-box"><div className="casino-table-left-box"><div className="casino-table-header"><div className="casino-nation-detail">Player A</div></div><div className="casino-table-body"><div className="casino-table-row"><div className="casino-odds-box">Player A</div><div className="casino-odds-box">3 Baccarat A</div><div className="casino-odds-box">Total A</div><div className="casino-odds-box">Pair Plus A</div></div><div className="casino-table-row"><div className="casino-odds-box back suspended-box"><span className="casino-odds">0</span></div><div className="casino-odds-box back suspended-box"><span className="casino-odds">0</span></div><div className="casino-odds-box back suspended-box"><span className="casino-odds">0</span></div><div className="casino-odds-box back suspended-box"><span className="casino-odds">A</span></div></div></div></div><div className="teenpatti20-other-oods d-md-none"><div className="casino-table-left-box"><div className="casino-odds-box back suspended-box"><div>
                         <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/spade.png" />
                         <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/club.png" /></div><div><span className="casino-odds">0</span></div></div><div className="casino-odds-box back suspended-box"><div>
                           <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/heart.png" />
                           <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/diamond.png" /></div><div><span className="casino-odds">0</span></div></div></div></div><div className="casino-table-right-box"><div className="casino-table-header"><div className="casino-nation-detail">Player B</div></div><div className="casino-table-body"><div className="casino-table-row"><div className="casino-odds-box">Player B</div><div className="casino-odds-box">3 Baccarat B</div><div className="casino-odds-box">Total B</div><div className="casino-odds-box">Pair Plus B</div></div><div className="casino-table-row"><div className="casino-odds-box back suspended-box"><span className="casino-odds">0</span></div><div className="casino-odds-box back suspended-box"><span className="casino-odds">0</span></div><div className="casino-odds-box back suspended-box"><span className="casino-odds">0</span></div><div className="casino-odds-box back suspended-box"><span className="casino-odds">B</span></div></div></div></div><div className="teenpatti20-other-oods d-md-none"><div className="casino-table-right-box"><div className="casino-odds-box back suspended-box"><div>
                             <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/spade.png" />
                             <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/club.png" /></div><div><span className="casino-odds">0</span></div></div><div className="casino-odds-box back suspended-box"><div>
                               <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/heart.png" />
                               <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/diamond.png" /></div><div><span className="casino-odds">0</span></div></div></div></div></div><div className="teenpatti20-other-oods d-none d-md-flex"><div className="casino-table-left-box"><div className="casino-odds-box back suspended-box"><div>
                                 <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/spade.png" />
                                 <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/club.png" /></div><div><span className="casino-odds">0</span></div></div><div className="casino-odds-box back suspended-box"><div>
                                   <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/heart.png" />
                                   <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/diamond.png" /></div><div><span className="casino-odds">0</span></div></div></div><div className="casino-table-right-box"><div className="casino-odds-box back suspended-box"><div>
                                     <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/spade.png" />
                                     <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/club.png" /></div><div><span className="casino-odds">0</span></div></div><div className="casino-odds-box back suspended-box"><div>
                                       <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/heart.png" />
                                       <img src="https://versionobj.ecoassetsservice.com/v28/static/front/img/icons/diamond.png" /></div><div><span className="casino-odds">0</span></div></div></div></div></div><div className="casino-last-result-title"><span>Last Result</span><span><a href="/casino-results/teen20c">View All</a></span></div><div className="casino-last-results"><span className="result result-b">B</span><span className="result result-b">B</span><span className="result result-a">A</span><span className="result result-b">B</span><span className="result result-a">A</span><span className="result result-a">A</span><span className="result result-a">A</span><span className="result result-a">A</span><span className="result result-a">A</span><span className="result result-b">B</span></div></div></div><div className="d-none"><div className="table-responsive"><table className="table"><thead><tr><th>Matched Bet</th><th className="text-end">Odds</th><th className="text-end">Stake</th></tr></thead><tbody></tbody></table></div></div></div></div><div className="sidebar right-sidebar casino-right-sidebar sticky"><div className="sidebar-box my-bet-container"><div className="sidebar-title"><h4>My Bet</h4></div><div className="my-bets"><div className="table-responsive"><table className="table"><thead><tr><th>Matched Bet</th><th className="text-end">Odds</th><th className="text-end">Stake</th></tr></thead><tbody></tbody></table></div></div></div></div></div>
  
    </div>
  )
}

export default TeenPattiC
